name: chatbot1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_generative_ai: ^0.4.3
  google_fonts: ^6.2.1
  camera: ^0.10.5+9
  gap: ^3.0.1
  external_path: ^1.0.3
  media_scanner: ^2.1.0
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  speech_to_text: ^6.6.2
  highlight_text: ^1.7.0
  avatar_glow: ^3.0.1 
  flutter_tts: ^4.0.2
  tflite: ^1.1.2
  path_provider: ^2.1.3
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - asset/

  fonts:
    - family: Museo
      fonts:
        - asset: Fonts\MuseoSans_500_Italic.otf
          style: italic
  
    - family: Grandstander
      fonts:
        - asset: Grandstander\static\Grandstander-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
