// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-CDKunr2U0rdSnZMRegm0S37sgwpf7t8',
    appId: '1:449802593207:web:ec6b5cf1b4b6215bb1be32',
    messagingSenderId: '449802593207',
    projectId: 'insightai-bbb17',
    authDomain: 'insightai-bbb17.firebaseapp.com',
    storageBucket: 'insightai-bbb17.appspot.com',
    measurementId: 'G-G67B54LYDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO6Rz4z9SoUNIVuVaqrHLK7NHxZbod6Q4',
    appId: '1:449802593207:android:ac076c9010dedc8bb1be32',
    messagingSenderId: '449802593207',
    projectId: 'insightai-bbb17',
    storageBucket: 'insightai-bbb17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQpprxk6bcmdHa8e9vW_sOlwaLdM6mXaU',
    appId: '1:449802593207:ios:ca4d9e3d85df08a3b1be32',
    messagingSenderId: '449802593207',
    projectId: 'insightai-bbb17',
    storageBucket: 'insightai-bbb17.appspot.com',
    iosBundleId: 'com.example.chatbot1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQpprxk6bcmdHa8e9vW_sOlwaLdM6mXaU',
    appId: '1:449802593207:ios:ca4d9e3d85df08a3b1be32',
    messagingSenderId: '449802593207',
    projectId: 'insightai-bbb17',
    storageBucket: 'insightai-bbb17.appspot.com',
    iosBundleId: 'com.example.chatbot1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-CDKunr2U0rdSnZMRegm0S37sgwpf7t8',
    appId: '1:449802593207:web:b3ac5841291bd0a6b1be32',
    messagingSenderId: '449802593207',
    projectId: 'insightai-bbb17',
    authDomain: 'insightai-bbb17.firebaseapp.com',
    storageBucket: 'insightai-bbb17.appspot.com',
    measurementId: 'G-KE9Q8Z3FP0',
  );
}
